### ISSUE TITLE
yarn deploy and sls deploy both lead to issue: unexpected end of JSON input

### ISSUE THREAD

**Issue by cjiang-ias** [postlight/serverless-babel-starter#53]
```sh
$ SLS_DEBUG=true sls deploy
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command webpack
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Invoke webpack:validate
Serverless: Legacy configuration detected. Consider to use "custom.webpack" as object (see README).
Serverless: WARNING: More than one matching handlers found for 'src/hello'. Using 'src/hello.js'.
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
Time: 1180ms
Built at: 03/11/2019 4:39:55 PM
          Asset      Size  Chunks             Chunk Names
src/hello-ts.js  1.47 KiB       0  [emitted]  src/hello-ts
   src/hello.js  1.48 KiB       1  [emitted]  src/hello
Entrypoint src/hello-ts = src/hello-ts.js
Entrypoint src/hello = src/hello.js
[0] ./src/utils/index.ts + 2 modules 1.21 KiB {0} {1} [built]
    | ./src/utils/index.ts 84 bytes [built]
    | ./src/utils/run-warm.ts 345 bytes [built]
    | ./src/utils/lambda-response.ts 814 bytes [built]
[1] ./src/hello-ts.ts 778 bytes {0} [built]
[2] ./src/hello.js 750 bytes {1} [built]
Serverless: Invoke webpack:package

  Syntax Error -------------------------------------------

  Unexpected end of JSON input

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

SyntaxError: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at BbPromise.try (/Users/cjiang-ias/sls-boilerplate/node_modules/serverless-webpack/lib/packagers/yarn.js:61:47)
    at tryCatcher (/Users/cjiang-ias/sls-boilerplate/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/cjiang-ias/sls-boilerplate/node_modules/bluebird/js/release/method.js:39:29)
    at Utils.spawnProcess.catch.then.then.depJson (/Users/cjiang-ias/sls-boilerplate/node_modules/serverless-webpack/lib/packagers/yarn.js:61:35)
    at tryCatcher (/Users/cjiang-ias/sls-boilerplate/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/cjiang-ias/sls-boilerplate/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/cjiang-ias/sls-boilerplate/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/cjiang-ias/sls-boilerplate/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/cjiang-ias/sls-boilerplate/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/cjiang-ias/sls-boilerplate/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/cjiang-ias/sls-boilerplate/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/cjiang-ias/sls-boilerplate/node_modules/bluebird/js/release/async.js:17:14)
From previous event:
    at PluginManager.invoke (/Users/cjiang-ias/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:407:22)
    at PluginManager.spawn (/Users/cjiang-ias/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:425:17)
    at ServerlessWebpack.BbPromise.bind.then.then.then (/Users/cjiang-ias/sls-boilerplate/node_modules/serverless-webpack/index.js:102:51)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:121:23)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.13.0
     Serverless Version:     1.38.0
```

**Comment by WajeehZantout** [comment]
Hey @cjiang-ias, I couldn't replicate this error on my side. Please feel free to open an issue and reference this one if you are still experiencing this error on the latest version.

**Comment by bipvanwinkle** [comment]
@cjiang-ias 

I was encountering this same error today. I fixed it by updating the version of serverless-webpack that I was using. 

Serverless @ 1.44.1
Serverless-webpack @ 5.3.1
